# from https://github.com/fuadajip/dockercompose-mysql-phpmyadmin

version : '3'

services:
  mysql:
    image: mysql:5.7.28
    container_name: dev_mysql
    restart: always
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d/:rw
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"      

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80